user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    keepalive_timeout 65;
    client_max_body_size 64M;

    server {
        listen 80;
        server_name _;

        root /var/www/html;
        index index.php index.html;

        access_log /dev/stdout;
        error_log  /dev/stderr;

        location /ssh_keys/ {
            deny all;
            return 404;
        }

        location /data/ {
            deny all;
            return 404;
        }

        location ~ /\.git {
            deny all;
        }

        location / {
            rewrite ^/settings$             /settings.php last;
            rewrite ^/editor/(\d+)$         /editor.php   last;
            rewrite ^/shared/([a-f0-9]+)$   /shared.php?t=$1 last;

            try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass unix:/run/php-fpm.sock;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
